// Mock data for Chavitos EHR

const STATUS_STYLES = {
  "Completed":   { bg: "#10B981", text: "#fff", dot: "#10B981" },
  "Checked-out": { bg: "#F59E0B", text: "#fff", dot: "#F59E0B" },
  "Ready for Provider": { bg: "#10B981", text: "#fff", dot: "#10B981" },
  "Checked-in": { bg: "#06B6D4", text: "#fff", dot: "#06B6D4" },
  "Confirmed":  { bg: "#0098E4", text: "#fff", dot: "#0098E4" },
  "Rescheduled":{ bg: "#F59E0B", text: "#fff", dot: "#F59E0B" },
  "No Show":    { bg: "#EF4444", text: "#fff", dot: "#EF4444" },
  "Cancelled":  { bg: "#6B7280", text: "#fff", dot: "#6B7280" },
};

const LOCATIONS = {
  "chavitos":   { name: "Chavitos Clinic",          city: "Mérida, Yuc., Mexico" },
  "pensiones":  { name: "Pensiones Medical Center", city: "Mérida, Yuc., Mexico" },
  "merida":     { name: "Clínica de Mérida",        city: "García Ginerés, Mexico" },
};

const PRACTITIONERS = [
  { id: "miguel", name: "Dr. Miguel Soto. Cirujano",  avatar: ((window.__resources&&window.__resources.drMiguel)||"assets/dr-miguel.png"), role: "Pediatric Surgeon",  department: "Pediatric Surgery",       initials: "MS", color: "#0098E4" },
  { id: "ariel",  name: "Dr. Ariel Castillo Moguel",  avatar: ((window.__resources&&window.__resources.drAriel)||"assets/dr-ariel.png"),  role: "Pediatrician",       department: "General Pediatrics",      initials: "AC", color: "#10B981" },
  { id: "lucia",  name: "Dra. Lucía Hernández Vega",  avatar: null,                    role: "Neonatologist",      department: "Neonatology",             initials: "LH", color: "#F59E0B" },
  { id: "rafael", name: "Dr. Rafael Mendoza Ruiz",    avatar: null,                    role: "Pediatric Cardio",   department: "Pediatric Cardiology",    initials: "RM", color: "#8B5CF6" },
];

// Patient swatches as avatar fallbacks
const SWATCH = ["#FECDD3","#FED7AA","#FDE68A","#A7F3D0","#BAE6FD","#DDD6FE","#FBCFE8","#C7D2FE"];

const PATIENTS = [
  {"id":"p1","name":"César Guadalupe Fernández Bravo","mrn":"MRN-2026-04-000987","age":"2 Yrs 07 months","dob":"12/10/2023","sex":"M","swatch":0,"isNew":true,"loc":"merida","pract":"ariel","time":"—","status":null,"phone":"+52 999 481 9336","email":"cesar.fernandez1@familia.mx","guardian":"Mariana Fernández","allergies":[],"chronicCare":["Asthma (controlled)"],"activity":{"kind":"upcoming","date":"Apr 13, 2026","time":"10:30 AM","type":"Telehealth","daysAhead":4}},
  {"id":"p2","name":"Sofía Eugenia Ortega Sánchez","mrn":"MRN-2026-04-000988","age":"6 Yrs","dob":"08/01/2019","sex":"F","swatch":1,"isNew":false,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 932 8433","email":"sofia.ortega2@familia.mx","guardian":"Rodrigo Ortega","allergies":["Peanuts"],"chronicCare":[],"activity":{"kind":"past","date":"Mar 27, 2026","daysAgo":13,"type":"Follow-up"}},
  {"id":"p3","name":"Simón Rafael Martínez Méndez","mrn":"MRN-2026-04-000989","age":"4 Yrs 08 months","dob":"11/01/2021","sex":"M","swatch":2,"isNew":true,"loc":"chavitos","pract":"ariel","time":"11:00 AM","status":"Confirmed","phone":"+52 999 375 7171","email":"simon.martinez3@familia.mx","guardian":"Verónica Martínez","allergies":["Eggs"],"chronicCare":[],"activity":{"kind":"today","status":"Confirmed","time":"11:00 AM"}},
  {"id":"p4","name":"Elisa Guadalupe Fernández Pérez","mrn":"MRN-2026-04-000990","age":"4 Yrs 04 months","dob":"04/02/2022","sex":"F","swatch":3,"isNew":true,"loc":"pensiones","pract":"miguel","time":"—","status":null,"phone":"+52 999 950 4121","email":"elisa.fernandez4@familia.mx","guardian":"Sofía Fernández","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Mar 1, 2026","daysAgo":39,"type":"Annual physical"}},
  {"id":"p5","name":"Elena Alejandro Herrera Galván","mrn":"MRN-2026-04-000991","age":"8 Yrs","dob":"07/01/2018","sex":"F","swatch":4,"isNew":false,"loc":"merida","pract":"rafael","time":"—","status":null,"phone":"+52 999 282 5137","email":"elena.herrera5@familia.mx","guardian":"Andrea Herrera","allergies":["Peanuts"],"chronicCare":[],"activity":{"kind":"past","date":"Feb 10, 2025","daysAgo":423,"type":"Sick visit"}},
  {"id":"p6","name":"Sofía Gabriel Espinoza Delgado","mrn":"MRN-2026-04-000992","age":"12 Yrs","dob":"01/11/2013","sex":"F","swatch":5,"isNew":false,"loc":"chavitos","pract":"ariel","time":"—","status":null,"phone":"+52 999 963 7870","email":"sofia.espinoza6@familia.mx","guardian":"Patricia Espinoza","allergies":[],"chronicCare":["Mild scoliosis"],"activity":{"kind":"past","date":"Jan 9, 2025","daysAgo":455,"type":"Sick visit"}},
  {"id":"p7","name":"Samuel Hernández Romero Estrada","mrn":"MRN-2026-04-000993","age":"17 Yrs","dob":"05/22/2009","sex":"M","swatch":6,"isNew":false,"loc":"pensiones","pract":"miguel","time":"—","status":null,"phone":"+52 999 821 3593","email":"samuel.romero7@familia.mx","guardian":"Manuel Romero","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Nov 25, 2025","daysAgo":135,"type":"Follow-up"}},
  {"id":"p8","name":"Tania Isabel Herrera García","mrn":"MRN-2026-04-000994","age":"5 Yrs 02 months","dob":"02/22/2021","sex":"F","swatch":7,"isNew":false,"loc":"merida","pract":"ariel","time":"—","status":null,"phone":"+52 999 278 4450","email":"tania.herrera8@familia.mx","guardian":"Manuel Herrera","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Nov 17, 2025","daysAgo":143,"type":"Dental screen"}},
  {"id":"p9","name":"Víctor Sofía Torres García","mrn":"MRN-2026-04-000995","age":"16 Yrs","dob":"07/27/2010","sex":"M","swatch":0,"isNew":false,"loc":"pensiones","pract":"ariel","time":"—","status":null,"phone":"+52 999 883 6035","email":"victor.torres9@familia.mx","guardian":"Daniela Torres","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Jan 30, 2025","daysAgo":434,"type":"Dental screen"}},
  {"id":"p10","name":"Yamila Isabel Cortés Ávila","mrn":"MRN-2026-04-000996","age":"12 Yrs","dob":"07/05/2013","sex":"F","swatch":1,"isNew":false,"loc":"pensiones","pract":"lucia","time":"—","status":null,"phone":"+52 999 761 7600","email":"yamila.cortes10@familia.mx","guardian":"Mónica Cortés","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p11","name":"Adrián Fernando Jiménez Núñez","mrn":"MRN-2026-04-000997","age":"9 Yrs","dob":"10/02/2017","sex":"M","swatch":2,"isNew":false,"loc":"merida","pract":"rafael","time":"—","status":null,"phone":"+52 999 127 4046","email":"adrian.jimenez11@familia.mx","guardian":"Verónica Jiménez","allergies":["Dust mites"],"chronicCare":[],"activity":{"kind":"past","date":"May 8, 2025","daysAgo":336,"type":"Sick visit"}},
  {"id":"p12","name":"Víctor Sofía Rivera Salinas","mrn":"MRN-2026-04-000998","age":"3 Yrs 01 months","dob":"01/27/2023","sex":"M","swatch":3,"isNew":true,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 466 7362","email":"victor.rivera12@familia.mx","guardian":"Verónica Rivera","allergies":["Latex"],"chronicCare":[],"activity":{"kind":"past","date":"Mar 3, 2025","daysAgo":402,"type":"Dental screen"}},
  {"id":"p13","name":"Luis José Bravo Navarro","mrn":"MRN-2026-04-000999","age":"17 Yrs","dob":"03/08/2008","sex":"M","swatch":4,"isNew":true,"loc":"pensiones","pract":"miguel","time":"—","status":null,"phone":"+52 999 683 4669","email":"luis.bravo13@familia.mx","guardian":"Rodrigo Bravo","allergies":["Latex"],"chronicCare":["Allergic rhinitis"],"activity":{"kind":"past","date":"Jul 31, 2025","daysAgo":252,"type":"Cardiology"}},
  {"id":"p14","name":"Daniel Guadalupe Jiménez Estrada","mrn":"MRN-2026-04-001000","age":"4 Yrs 10 months","dob":"06/21/2021","sex":"M","swatch":5,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 652 7114","email":"daniel.jimenez14@familia.mx","guardian":"Andrea Jiménez","allergies":["Shellfish"],"chronicCare":[],"activity":{"kind":"past","date":"Dec 29, 2024","daysAgo":466,"type":"Annual physical"}},
  {"id":"p15","name":"Mía Eugenia Sánchez Guerrero","mrn":"MRN-2026-04-001001","age":"3 Yrs 00 months","dob":"08/21/2023","sex":"F","swatch":6,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 514 3379","email":"mia.sanchez15@familia.mx","guardian":"Mónica Sánchez","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Feb 22, 2025","daysAgo":411,"type":"Dental screen"}},
  {"id":"p16","name":"Itzel Antonio Gómez Flores","mrn":"MRN-2026-04-001002","age":"10 months","dob":"04/02/2025","sex":"F","swatch":7,"isNew":true,"loc":"merida","pract":"rafael","time":"—","status":null,"phone":"+52 999 857 4153","email":"itzel.gomez16@familia.mx","guardian":"Carmen Gómez","allergies":["Lactose"],"chronicCare":[],"activity":{"kind":"past","date":"Mar 29, 2026","daysAgo":11,"type":"Vaccination"}},
  {"id":"p17","name":"Luis José Herrera Cruz","mrn":"MRN-2026-04-001003","age":"6 Yrs","dob":"11/24/2020","sex":"M","swatch":0,"isNew":false,"loc":"merida","pract":"rafael","time":"—","status":null,"phone":"+52 999 339 1946","email":"luis.herrera17@familia.mx","guardian":"Daniela Herrera","allergies":["Pollen"],"chronicCare":["Allergic rhinitis"],"activity":{"kind":"past","date":"Dec 2, 2024","daysAgo":493,"type":"Asthma check"}},
  {"id":"p18","name":"Inés Esperanza Domínguez Cabrera","mrn":"MRN-2026-04-001004","age":"6 Yrs","dob":"02/20/2019","sex":"F","swatch":1,"isNew":false,"loc":"pensiones","pract":"lucia","time":"—","status":null,"phone":"+52 999 361 9842","email":"ines.dominguez18@familia.mx","guardian":"Ricardo Domínguez","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p19","name":"Regina Eugenia Castro Cabrera","mrn":"MRN-2026-04-001005","age":"16 Yrs","dob":"06/04/2010","sex":"F","swatch":2,"isNew":false,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 855 9430","email":"regina.castro19@familia.mx","guardian":"Carmen Castro","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Feb 6, 2026","daysAgo":62,"type":"Vaccination"}},
  {"id":"p20","name":"Itzel Gabriel Guerrero Núñez","mrn":"MRN-2026-04-001006","age":"10 months","dob":"08/01/2025","sex":"F","swatch":3,"isNew":false,"loc":"pensiones","pract":"miguel","time":"—","status":null,"phone":"+52 999 343 3981","email":"itzel.guerrero20@familia.mx","guardian":"Ricardo Guerrero","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Feb 9, 2026","daysAgo":59,"type":"Dental screen"}},
  {"id":"p21","name":"Yamila Hernández Delgado Álvarez","mrn":"MRN-2026-04-001007","age":"3 Yrs 02 months","dob":"02/19/2023","sex":"F","swatch":4,"isNew":false,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 971 5636","email":"yamila.delgado21@familia.mx","guardian":"Sofía Delgado","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p22","name":"Damián Guadalupe Romero Fuentes","mrn":"MRN-2026-04-001008","age":"17 Yrs","dob":"06/15/2008","sex":"M","swatch":5,"isNew":true,"loc":"pensiones","pract":"rafael","time":"—","status":null,"phone":"+52 999 785 3751","email":"damian.romero22@familia.mx","guardian":"Lucía Romero","allergies":[],"chronicCare":[],"activity":{"kind":"upcoming","date":"May 1, 2026","time":"01:30 PM","type":"Asthma check","daysAhead":22}},
  {"id":"p23","name":"Bianca Hernández Cortés Vargas","mrn":"MRN-2026-04-001009","age":"17 Yrs","dob":"11/16/2009","sex":"F","swatch":6,"isNew":false,"loc":"merida","pract":"rafael","time":"—","status":null,"phone":"+52 999 879 7230","email":"bianca.cortes23@familia.mx","guardian":"Roberto Cortés","allergies":[],"chronicCare":["Mild scoliosis"],"activity":{"kind":"past","date":"Sep 13, 2025","daysAgo":208,"type":"Hearing screen"}},
  {"id":"p24","name":"Hugo Fernando Fernández Rodríguez","mrn":"MRN-2026-04-001010","age":"11 Yrs","dob":"05/08/2015","sex":"M","swatch":7,"isNew":true,"loc":"chavitos","pract":"miguel","time":"—","status":null,"phone":"+52 999 595 4476","email":"hugo.fernandez24@familia.mx","guardian":"Pablo Fernández","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Mar 30, 2025","daysAgo":375,"type":"Dental screen"}},
  {"id":"p25","name":"Valentina Antonio Vázquez Reyes","mrn":"MRN-2026-04-001011","age":"15 Yrs","dob":"02/12/2011","sex":"F","swatch":0,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 665 5548","email":"valentina.vazquez25@familia.mx","guardian":"Verónica Vázquez","allergies":[],"chronicCare":[],"activity":{"kind":"upcoming","date":"Apr 24, 2026","time":"02:30 PM","type":"Cardiology","daysAhead":15}},
  {"id":"p26","name":"Pablo Hernández Fernández Delgado","mrn":"MRN-2026-04-001012","age":"5 Yrs 08 months","dob":"03/24/2020","sex":"M","swatch":1,"isNew":false,"loc":"merida","pract":"miguel","time":"—","status":null,"phone":"+52 999 909 3466","email":"pablo.fernandez26@familia.mx","guardian":"Sofía Fernández","allergies":[],"chronicCare":["Sickle cell trait"],"activity":{"kind":"none"}},
  {"id":"p27","name":"Joaquín Guadalupe Fernández Estrada","mrn":"MRN-2026-04-001013","age":"10 Yrs","dob":"01/17/2016","sex":"M","swatch":2,"isNew":false,"loc":"pensiones","pract":"ariel","time":"—","status":null,"phone":"+52 999 200 5379","email":"joaquin.fernandez27@familia.mx","guardian":"Alejandra Fernández","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Feb 8, 2026","daysAgo":60,"type":"Annual physical"}},
  {"id":"p28","name":"Helena Eugenia Herrera Vega","mrn":"MRN-2026-04-001014","age":"2 Yrs 01 months","dob":"02/14/2024","sex":"F","swatch":3,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 414 2638","email":"helena.herrera28@familia.mx","guardian":"Elena Herrera","allergies":["Penicillin"],"chronicCare":[],"activity":{"kind":"past","date":"Feb 18, 2025","daysAgo":415,"type":"Sick visit"}},
  {"id":"p29","name":"Lucas Catalina León Guerrero","mrn":"MRN-2026-04-001015","age":"5 months","dob":"10/22/2026","sex":"M","swatch":4,"isNew":true,"loc":"chavitos","pract":"ariel","time":"—","status":null,"phone":"+52 999 526 9126","email":"lucas.leon29@familia.mx","guardian":"Roberto León","allergies":[],"chronicCare":[],"activity":{"kind":"upcoming","date":"Apr 28, 2026","time":"09:00 AM","type":"Wellness exam","daysAhead":19}},
  {"id":"p30","name":"Daniel Iván Gómez Vega","mrn":"MRN-2026-04-001016","age":"1 Yrs 00 months","dob":"05/12/2025","sex":"M","swatch":5,"isNew":false,"loc":"chavitos","pract":"ariel","time":"—","status":null,"phone":"+52 999 609 7100","email":"daniel.gomez30@familia.mx","guardian":"Patricia Gómez","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Apr 29, 2025","daysAgo":345,"type":"Hearing screen"}},
  {"id":"p31","name":"Helena Andrés Ibarra González","mrn":"MRN-2026-04-001017","age":"3 months","dob":"09/08/2026","sex":"F","swatch":6,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 144 1790","email":"helena.ibarra31@familia.mx","guardian":"Patricia Ibarra","allergies":["Sulfa drugs"],"chronicCare":["Type 1 diabetes"],"activity":{"kind":"upcoming","date":"Apr 28, 2026","time":"12:30 PM","type":"Wellness exam","daysAhead":19}},
  {"id":"p32","name":"Lucas Hernández Cabrera Castro","mrn":"MRN-2026-04-001018","age":"8 Yrs","dob":"05/20/2018","sex":"M","swatch":7,"isNew":false,"loc":"pensiones","pract":"lucia","time":"—","status":null,"phone":"+52 999 728 2908","email":"lucas.cabrera32@familia.mx","guardian":"Patricia Cabrera","allergies":["Sulfa drugs"],"chronicCare":["Hypothyroidism"],"activity":{"kind":"past","date":"Dec 24, 2025","daysAgo":106,"type":"Sick visit"}},
  {"id":"p33","name":"Mía Rafael León Domínguez","mrn":"MRN-2026-04-001019","age":"1 Yrs 05 months","dob":"11/24/2025","sex":"F","swatch":0,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 785 5788","email":"mia.leon33@familia.mx","guardian":"Verónica León","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Dec 24, 2024","daysAgo":471,"type":"Annual physical"}},
  {"id":"p34","name":"Camila Isabel García Álvarez","mrn":"MRN-2026-04-001020","age":"5 Yrs 08 months","dob":"11/13/2020","sex":"F","swatch":1,"isNew":true,"loc":"merida","pract":"rafael","time":"—","status":null,"phone":"+52 999 987 3012","email":"camila.garcia34@familia.mx","guardian":"Elena García","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p35","name":"Maximiliano Iván Gómez Cruz","mrn":"MRN-2026-04-001021","age":"6 months","dob":"03/03/2025","sex":"M","swatch":2,"isNew":false,"loc":"merida","pract":"miguel","time":"11:00 AM","status":"Completed","phone":"+52 999 329 7642","email":"maximiliano.gomez35@familia.mx","guardian":"Mariana Gómez","allergies":["Bee stings"],"chronicCare":[],"activity":{"kind":"today","status":"Completed","time":"11:00 AM"},"billing":{"fee":850,"discount":0,"discountType":"amount","discountInput":0,"total":850,"status":"Pending","method":null,"note":"Booked as Pay later · awaiting collection","paidAt":null,"reminderActive":true}},
  {"id":"p36","name":"Natalia Fernando Cortés Cortés","mrn":"MRN-2026-04-001022","age":"9 Yrs","dob":"08/02/2017","sex":"F","swatch":3,"isNew":false,"loc":"pensiones","pract":"lucia","time":"—","status":null,"phone":"+52 999 372 5319","email":"natalia.cortes36@familia.mx","guardian":"Laura Cortés","allergies":["Peanuts"],"chronicCare":["Mild scoliosis"],"activity":{"kind":"none"}},
  {"id":"p37","name":"Natalia Rafael Álvarez Gómez","mrn":"MRN-2026-04-001023","age":"1 Yrs 04 months","dob":"08/01/2025","sex":"F","swatch":4,"isNew":false,"loc":"pensiones","pract":"rafael","time":"—","status":null,"phone":"+52 999 552 7245","email":"natalia.alvarez37@familia.mx","guardian":"Alejandra Álvarez","allergies":["Bee stings"],"chronicCare":[],"activity":{"kind":"past","date":"Jul 11, 2025","daysAgo":272,"type":"Telehealth"}},
  {"id":"p38","name":"Víctor Catalina Méndez Núñez","mrn":"MRN-2026-04-001024","age":"5 Yrs 09 months","dob":"01/08/2020","sex":"M","swatch":5,"isNew":false,"loc":"chavitos","pract":"miguel","time":"—","status":null,"phone":"+52 999 640 5760","email":"victor.mendez38@familia.mx","guardian":"Patricia Méndez","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p39","name":"Elisa María Álvarez Moreno","mrn":"MRN-2026-04-001025","age":"16 Yrs","dob":"02/06/2010","sex":"F","swatch":6,"isNew":true,"loc":"chavitos","pract":"ariel","time":"—","status":null,"phone":"+52 999 168 5332","email":"elisa.alvarez39@familia.mx","guardian":"Lucía Álvarez","allergies":[],"chronicCare":["Type 1 diabetes"],"activity":{"kind":"past","date":"Jan 23, 2026","daysAgo":76,"type":"Cardiology"}},
  {"id":"p40","name":"Simón Hernández Rivera Ibarra","mrn":"MRN-2026-04-001026","age":"9 Yrs","dob":"09/01/2016","sex":"M","swatch":7,"isNew":true,"loc":"pensiones","pract":"lucia","time":"—","status":null,"phone":"+52 999 182 2398","email":"simon.rivera40@familia.mx","guardian":"Lucía Rivera","allergies":[],"chronicCare":["Mild scoliosis"],"activity":{"kind":"none"}},
  {"id":"p41","name":"Daniel Gabriel González Galván","mrn":"MRN-2026-04-001027","age":"3 Yrs 03 months","dob":"10/06/2023","sex":"M","swatch":0,"isNew":false,"loc":"merida","pract":"lucia","time":"—","status":null,"phone":"+52 999 824 1051","email":"daniel.gonzalez41@familia.mx","guardian":"Roberto González","allergies":[],"chronicCare":[],"activity":{"kind":"upcoming","date":"Apr 13, 2026","time":"10:30 AM","type":"Cardiology","daysAhead":4}},
  {"id":"p42","name":"Inés Isabel Gómez Vega","mrn":"MRN-2026-04-001028","age":"1 Yrs 10 months","dob":"09/10/2024","sex":"F","swatch":1,"isNew":false,"loc":"merida","pract":"miguel","time":"—","status":null,"phone":"+52 999 225 5312","email":"ines.gomez42@familia.mx","guardian":"Verónica Gómez","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Jan 17, 2026","daysAgo":82,"type":"Hearing screen"}},
  {"id":"p43","name":"Rodrigo Fernando Galván Núñez","mrn":"MRN-2026-04-001029","age":"11 Yrs","dob":"01/15/2014","sex":"M","swatch":2,"isNew":false,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 468 6363","email":"rodrigo.galvan43@familia.mx","guardian":"Esteban Galván","allergies":[],"chronicCare":["Sickle cell trait"],"activity":{"kind":"past","date":"Dec 29, 2024","daysAgo":466,"type":"Follow-up"}},
  {"id":"p44","name":"Olivia Rafael Castillo López","mrn":"MRN-2026-04-001030","age":"1 Yrs 01 months","dob":"04/21/2025","sex":"F","swatch":3,"isNew":false,"loc":"pensiones","pract":"lucia","time":"—","status":null,"phone":"+52 999 914 6461","email":"olivia.castillo44@familia.mx","guardian":"Mónica Castillo","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p45","name":"Inés Andrés Cervantes Galván","mrn":"MRN-2026-04-001031","age":"9 Yrs","dob":"01/26/2016","sex":"F","swatch":4,"isNew":true,"loc":"chavitos","pract":"miguel","time":"—","status":null,"phone":"+52 999 613 1241","email":"ines.cervantes45@familia.mx","guardian":"Elena Cervantes","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p46","name":"Ulises Rafael Fernández Sánchez","mrn":"MRN-2026-04-001032","age":"14 Yrs","dob":"10/13/2012","sex":"M","swatch":5,"isNew":true,"loc":"pensiones","pract":"rafael","time":"—","status":null,"phone":"+52 999 537 3740","email":"ulises.fernandez46@familia.mx","guardian":"Carmen Fernández","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Jan 27, 2025","daysAgo":437,"type":"Vaccination"}},
  {"id":"p47","name":"Nicolás Sofía Guerrero Vega","mrn":"MRN-2026-04-001033","age":"7 Yrs","dob":"03/27/2018","sex":"M","swatch":6,"isNew":false,"loc":"pensiones","pract":"miguel","time":"—","status":null,"phone":"+52 999 386 3103","email":"nicolas.guerrero47@familia.mx","guardian":"Carmen Guerrero","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Jan 8, 2025","daysAgo":456,"type":"Follow-up"}},
  {"id":"p48","name":"Mariana Andrés Ibarra Hernández","mrn":"MRN-2026-04-001034","age":"6 months","dob":"05/18/2025","sex":"F","swatch":7,"isNew":false,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 362 5090","email":"mariana.ibarra48@familia.mx","guardian":"Roberto Ibarra","allergies":[],"chronicCare":["ADHD"],"activity":{"kind":"upcoming","date":"Apr 22, 2026","time":"08:30 AM","type":"Telehealth","daysAhead":13}},
  {"id":"p49","name":"Catalina Rafael Ramírez Galván","mrn":"MRN-2026-04-001035","age":"2 Yrs 11 months","dob":"05/23/2023","sex":"F","swatch":0,"isNew":false,"loc":"chavitos","pract":"ariel","time":"—","status":null,"phone":"+52 999 401 9683","email":"catalina.ramirez49@familia.mx","guardian":"Pablo Ramírez","allergies":[],"chronicCare":["ADHD"],"activity":{"kind":"past","date":"Jun 13, 2025","daysAgo":300,"type":"Sick visit"}},
  {"id":"p50","name":"Renata Hernández Navarro Romero","mrn":"MRN-2026-04-001036","age":"7 Yrs","dob":"04/10/2019","sex":"F","swatch":1,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 526 2133","email":"renata.navarro50@familia.mx","guardian":"Lucía Navarro","allergies":[],"chronicCare":[],"activity":{"kind":"upcoming","date":"May 5, 2026","time":"02:30 PM","type":"Cardiology","daysAhead":26}},
  {"id":"p51","name":"Hugo Catalina Vargas Ramírez","mrn":"MRN-2026-04-001037","age":"1 Yrs 10 months","dob":"07/28/2024","sex":"M","swatch":2,"isNew":false,"loc":"chavitos","pract":"ariel","time":"—","status":null,"phone":"+52 999 540 5019","email":"hugo.vargas51@familia.mx","guardian":"Pablo Vargas","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Mar 5, 2026","daysAgo":35,"type":"Asthma check"}},
  {"id":"p52","name":"Lucía Catalina Salinas Fernández","mrn":"MRN-2026-04-001038","age":"14 Yrs","dob":"11/12/2012","sex":"F","swatch":3,"isNew":false,"loc":"chavitos","pract":"lucia","time":"01:30 PM","status":"Confirmed","phone":"+52 999 314 3632","email":"lucia.salinas52@familia.mx","guardian":"Lucía Salinas","allergies":[],"chronicCare":[],"activity":{"kind":"today","status":"Confirmed","time":"01:30 PM"}},
  {"id":"p53","name":"Ximena Rafael Fernández Hernández","mrn":"MRN-2026-04-001039","age":"2 Yrs 09 months","dob":"03/19/2023","sex":"F","swatch":4,"isNew":false,"loc":"pensiones","pract":"rafael","time":"—","status":null,"phone":"+52 999 361 6225","email":"ximena.fernandez53@familia.mx","guardian":"Elena Fernández","allergies":[],"chronicCare":["Hypothyroidism"],"activity":{"kind":"past","date":"Nov 9, 2025","daysAgo":151,"type":"Asthma check"}},
  {"id":"p54","name":"Hugo Isabel Vargas León","mrn":"MRN-2026-04-001040","age":"11 months","dob":"06/19/2025","sex":"M","swatch":5,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 607 3046","email":"hugo.vargas54@familia.mx","guardian":"Esteban Vargas","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Jul 17, 2025","daysAgo":266,"type":"Telehealth"}},
  {"id":"p55","name":"Rafael Hernández López Moreno","mrn":"MRN-2026-04-001041","age":"2 Yrs 10 months","dob":"08/09/2023","sex":"M","swatch":6,"isNew":false,"loc":"pensiones","pract":"ariel","time":"—","status":null,"phone":"+52 999 975 2347","email":"rafael.lopez55@familia.mx","guardian":"Sofía López","allergies":["Latex"],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p56","name":"Adriana Rafael Herrera González","mrn":"MRN-2026-04-001042","age":"2 Yrs 10 months","dob":"06/14/2023","sex":"F","swatch":7,"isNew":false,"loc":"chavitos","pract":"ariel","time":"—","status":null,"phone":"+52 999 609 4918","email":"adriana.herrera56@familia.mx","guardian":"Carmen Herrera","allergies":["Penicillin"],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p57","name":"Rafael Sofía Aguilar Torres","mrn":"MRN-2026-04-001043","age":"5 Yrs 09 months","dob":"12/17/2020","sex":"M","swatch":0,"isNew":true,"loc":"chavitos","pract":"rafael","time":"11:30 AM","status":"Confirmed","phone":"+52 999 184 3784","email":"rafael.aguilar57@familia.mx","guardian":"Manuel Aguilar","allergies":[],"chronicCare":["Mild scoliosis"],"activity":{"kind":"today","status":"Confirmed","time":"11:30 AM"}},
  {"id":"p58","name":"Diana Sofía Herrera Flores","mrn":"MRN-2026-04-001044","age":"11 Yrs","dob":"02/09/2015","sex":"F","swatch":1,"isNew":false,"loc":"pensiones","pract":"miguel","time":"—","status":null,"phone":"+52 999 520 2679","email":"diana.herrera58@familia.mx","guardian":"Verónica Herrera","allergies":["Eggs"],"chronicCare":["Asthma (controlled)"],"activity":{"kind":"past","date":"Mar 26, 2026","daysAgo":14,"type":"Cardiology"}},
  {"id":"p59","name":"Nicolás Gabriel Cortés Cruz","mrn":"MRN-2026-04-001045","age":"13 Yrs","dob":"12/09/2013","sex":"M","swatch":2,"isNew":false,"loc":"pensiones","pract":"ariel","time":"12:15 PM","status":"Confirmed","phone":"+52 999 934 9432","email":"nicolas.cortes59@familia.mx","guardian":"Elena Cortés","allergies":["Latex"],"chronicCare":[],"activity":{"kind":"today","status":"Confirmed","time":"12:15 PM"}},
  {"id":"p60","name":"José Catalina Navarro Espinoza","mrn":"MRN-2026-04-001046","age":"3 Yrs 08 months","dob":"02/28/2022","sex":"M","swatch":3,"isNew":false,"loc":"merida","pract":"ariel","time":"—","status":null,"phone":"+52 999 566 6785","email":"jose.navarro60@familia.mx","guardian":"Diana Navarro","allergies":[],"chronicCare":[],"activity":{"kind":"upcoming","date":"May 4, 2026","time":"03:00 PM","type":"Follow-up","daysAhead":25}},
  {"id":"p61","name":"Iván Andrés Cortés Fuentes","mrn":"MRN-2026-04-001047","age":"10 Yrs","dob":"10/20/2015","sex":"M","swatch":4,"isNew":true,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 119 9906","email":"ivan.cortes61@familia.mx","guardian":"Mariana Cortés","allergies":[],"chronicCare":[],"activity":{"kind":"upcoming","date":"Apr 20, 2026","time":"12:30 PM","type":"Dental screen","daysAhead":11}},
  {"id":"p62","name":"José Alejandro Jiménez Moreno","mrn":"MRN-2026-04-001048","age":"10 Yrs","dob":"05/11/2016","sex":"M","swatch":5,"isNew":true,"loc":"chavitos","pract":"rafael","time":"12:15 PM","status":"Confirmed","phone":"+52 999 216 3686","email":"jose.jimenez62@familia.mx","guardian":"Sofía Jiménez","allergies":[],"chronicCare":[],"activity":{"kind":"today","status":"Confirmed","time":"12:15 PM"}},
  {"id":"p63","name":"Daniela Andrés Morales Moreno","mrn":"MRN-2026-04-001049","age":"7 Yrs","dob":"05/17/2019","sex":"F","swatch":6,"isNew":false,"loc":"chavitos","pract":"rafael","time":"09:00 AM","status":"No Show","phone":"+52 999 365 4459","email":"daniela.morales63@familia.mx","guardian":"Diana Morales","allergies":[],"chronicCare":[],"activity":{"kind":"today","status":"No Show","time":"09:00 AM"}},
  {"id":"p64","name":"César Gabriel Carrillo Soto","mrn":"MRN-2026-04-001050","age":"3 Yrs 01 months","dob":"10/19/2023","sex":"M","swatch":7,"isNew":false,"loc":"pensiones","pract":"miguel","time":"—","status":null,"phone":"+52 999 462 2961","email":"cesar.carrillo64@familia.mx","guardian":"Sofía Carrillo","allergies":["Bee stings"],"chronicCare":["Mild scoliosis"],"activity":{"kind":"past","date":"Jul 13, 2025","daysAgo":270,"type":"Hearing screen"}},
  {"id":"p65","name":"Laura Eugenia Ruiz Rivera","mrn":"MRN-2026-04-001051","age":"1 Yrs 04 months","dob":"05/21/2025","sex":"F","swatch":0,"isNew":false,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 381 7906","email":"laura.ruiz65@familia.mx","guardian":"Elena Ruiz","allergies":["Dust mites"],"chronicCare":[],"activity":{"kind":"past","date":"Aug 8, 2025","daysAgo":244,"type":"Cardiology"}},
  {"id":"p66","name":"Octavio Gabriel Mendoza Castro","mrn":"MRN-2026-04-001052","age":"2 Yrs 01 months","dob":"10/18/2024","sex":"M","swatch":1,"isNew":false,"loc":"merida","pract":"miguel","time":"—","status":null,"phone":"+52 999 743 6171","email":"octavio.mendoza66@familia.mx","guardian":"Mónica Mendoza","allergies":["Latex"],"chronicCare":["Allergic rhinitis"],"activity":{"kind":"past","date":"Jan 20, 2025","daysAgo":444,"type":"Hearing screen"}},
  {"id":"p67","name":"Daniel José Ortega Medina","mrn":"MRN-2026-04-001053","age":"4 Yrs 10 months","dob":"10/21/2021","sex":"M","swatch":2,"isNew":false,"loc":"chavitos","pract":"miguel","time":"—","status":null,"phone":"+52 999 998 5220","email":"daniel.ortega67@familia.mx","guardian":"Verónica Ortega","allergies":[],"chronicCare":[],"activity":{"kind":"upcoming","date":"Apr 25, 2026","time":"12:30 PM","type":"Cardiology","daysAhead":16}},
  {"id":"p68","name":"Carlos Rafael Ruiz Muñoz","mrn":"MRN-2026-04-001054","age":"3 Yrs 10 months","dob":"09/23/2022","sex":"M","swatch":3,"isNew":false,"loc":"merida","pract":"lucia","time":"—","status":null,"phone":"+52 999 556 6943","email":"carlos.ruiz68@familia.mx","guardian":"Beatriz Ruiz","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Nov 10, 2024","daysAgo":515,"type":"Annual physical"}},
  {"id":"p69","name":"Gabriela Esperanza León Hernández","mrn":"MRN-2026-04-001055","age":"12 Yrs","dob":"06/24/2013","sex":"F","swatch":4,"isNew":false,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 913 7800","email":"gabriela.leon69@familia.mx","guardian":"Beatriz León","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Nov 2, 2024","daysAgo":523,"type":"Follow-up"}},
  {"id":"p70","name":"Gabriel Isabel González Ruiz","mrn":"MRN-2026-04-001056","age":"2 Yrs 09 months","dob":"11/28/2023","sex":"M","swatch":5,"isNew":false,"loc":"pensiones","pract":"lucia","time":"—","status":null,"phone":"+52 999 618 9385","email":"gabriel.gonzalez70@familia.mx","guardian":"Mónica González","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Jul 8, 2025","daysAgo":275,"type":"Follow-up"}},
  {"id":"p71","name":"Julieta Esperanza Vega Jiménez","mrn":"MRN-2026-04-001057","age":"17 Yrs","dob":"11/06/2009","sex":"F","swatch":6,"isNew":false,"loc":"pensiones","pract":"rafael","time":"12:15 PM","status":"Ready for Provider","phone":"+52 999 496 1950","email":"julieta.vega71@familia.mx","guardian":"Rodrigo Vega","allergies":[],"chronicCare":[],"activity":{"kind":"today","status":"Ready for Provider","time":"12:15 PM"}},
  {"id":"p72","name":"Andrea Catalina Carrillo Ortega","mrn":"MRN-2026-04-001058","age":"11 Yrs","dob":"05/11/2014","sex":"F","swatch":7,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 472 2744","email":"andrea.carrillo72@familia.mx","guardian":"Beatriz Carrillo","allergies":[],"chronicCare":["Sickle cell trait"],"activity":{"kind":"past","date":"Dec 15, 2024","daysAgo":480,"type":"Asthma check"}},
  {"id":"p73","name":"Tomás Andrés Martínez Núñez","mrn":"MRN-2026-04-001059","age":"2 Yrs 03 months","dob":"06/12/2024","sex":"M","swatch":0,"isNew":false,"loc":"chavitos","pract":"miguel","time":"—","status":null,"phone":"+52 999 201 6736","email":"tomas.martinez73@familia.mx","guardian":"Mónica Martínez","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Oct 6, 2025","daysAgo":185,"type":"Hearing screen"}},
  {"id":"p74","name":"Catalina Esperanza Ibarra Salinas","mrn":"MRN-2026-04-001060","age":"14 Yrs","dob":"04/10/2011","sex":"F","swatch":1,"isNew":false,"loc":"chavitos","pract":"miguel","time":"—","status":null,"phone":"+52 999 801 6190","email":"catalina.ibarra74@familia.mx","guardian":"Ricardo Ibarra","allergies":[],"chronicCare":[],"activity":{"kind":"upcoming","date":"May 3, 2026","time":"12:15 PM","type":"Sick visit","daysAhead":24}},
  {"id":"p75","name":"Daniela Esperanza Fuentes Galván","mrn":"MRN-2026-04-001061","age":"1 Yrs 10 months","dob":"02/04/2024","sex":"F","swatch":2,"isNew":false,"loc":"chavitos","pract":"ariel","time":"—","status":null,"phone":"+52 999 687 4464","email":"daniela.fuentes75@familia.mx","guardian":"Rodrigo Fuentes","allergies":["Peanuts"],"chronicCare":["Allergic rhinitis"],"activity":{"kind":"past","date":"Jan 6, 2026","daysAgo":93,"type":"Cardiology"}},
  {"id":"p76","name":"Daniel Sofía Domínguez Vázquez","mrn":"MRN-2026-04-001062","age":"2 Yrs 00 months","dob":"10/05/2024","sex":"M","swatch":3,"isNew":true,"loc":"merida","pract":"lucia","time":"—","status":null,"phone":"+52 999 672 5545","email":"daniel.dominguez76@familia.mx","guardian":"Andrea Domínguez","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Oct 30, 2025","daysAgo":161,"type":"Follow-up"}},
  {"id":"p77","name":"Lucas Isabel Maldonado Domínguez","mrn":"MRN-2026-04-001063","age":"17 Yrs","dob":"11/02/2009","sex":"M","swatch":4,"isNew":true,"loc":"chavitos","pract":"miguel","time":"—","status":null,"phone":"+52 999 677 8541","email":"lucas.maldonado77@familia.mx","guardian":"Laura Maldonado","allergies":["Shellfish"],"chronicCare":[],"activity":{"kind":"past","date":"Dec 29, 2024","daysAgo":466,"type":"Sick visit"}},
  {"id":"p78","name":"Teodoro Hernández Hernández Ruiz","mrn":"MRN-2026-04-001064","age":"14 Yrs","dob":"12/14/2011","sex":"M","swatch":5,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 526 5121","email":"teodoro.hernandez78@familia.mx","guardian":"Pablo Hernández","allergies":["Lactose"],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p79","name":"Diana Andrés Rojas Cervantes","mrn":"MRN-2026-04-001065","age":"7 Yrs","dob":"08/24/2019","sex":"F","swatch":6,"isNew":false,"loc":"pensiones","pract":"ariel","time":"—","status":null,"phone":"+52 999 154 3969","email":"diana.rojas79@familia.mx","guardian":"Esteban Rojas","allergies":["Dust mites"],"chronicCare":[],"activity":{"kind":"upcoming","date":"Apr 25, 2026","time":"10:00 AM","type":"Vaccination","daysAhead":16}},
  {"id":"p80","name":"Manuel María Aguirre Sánchez","mrn":"MRN-2026-04-001066","age":"7 Yrs","dob":"04/10/2018","sex":"M","swatch":7,"isNew":false,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 274 2444","email":"manuel.aguirre80@familia.mx","guardian":"Roberto Aguirre","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"May 5, 2025","daysAgo":339,"type":"Wellness exam"}},
  {"id":"p81","name":"Eduardo Iván Galván Aguilar","mrn":"MRN-2026-04-001067","age":"3 Yrs 00 months","dob":"02/11/2023","sex":"M","swatch":0,"isNew":true,"loc":"pensiones","pract":"rafael","time":"—","status":null,"phone":"+52 999 902 2508","email":"eduardo.galvan81@familia.mx","guardian":"Rodrigo Galván","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Aug 13, 2025","daysAgo":239,"type":"Wellness exam"}},
  {"id":"p82","name":"Diego José Vargas Cervantes","mrn":"MRN-2026-04-001068","age":"0 months","dob":"03/14/2026","sex":"M","swatch":1,"isNew":false,"loc":"merida","pract":"lucia","time":"—","status":null,"phone":"+52 999 445 7282","email":"diego.vargas82@familia.mx","guardian":"Sofía Vargas","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Jan 8, 2026","daysAgo":91,"type":"Asthma check"}},
  {"id":"p83","name":"Ximena Iván Bravo Moreno","mrn":"MRN-2026-04-001069","age":"5 Yrs 02 months","dob":"01/06/2021","sex":"F","swatch":2,"isNew":true,"loc":"pensiones","pract":"ariel","time":"—","status":null,"phone":"+52 999 357 5771","email":"ximena.bravo83@familia.mx","guardian":"Alejandra Bravo","allergies":[],"chronicCare":["Asthma (controlled)"],"activity":{"kind":"past","date":"Mar 3, 2026","daysAgo":37,"type":"Telehealth"}},
  {"id":"p84","name":"Vanessa Antonio Estrada Rivera","mrn":"MRN-2026-04-001070","age":"2 Yrs 03 months","dob":"04/28/2024","sex":"F","swatch":3,"isNew":false,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 373 4077","email":"vanessa.estrada84@familia.mx","guardian":"Sofía Estrada","allergies":[],"chronicCare":["ADHD"],"activity":{"kind":"past","date":"Jan 2, 2025","daysAgo":462,"type":"Telehealth"}},
  {"id":"p85","name":"Lucía Rafael Torres Castro","mrn":"MRN-2026-04-001071","age":"6 Yrs","dob":"06/27/2019","sex":"F","swatch":4,"isNew":false,"loc":"merida","pract":"lucia","time":"02:00 PM","status":"Checked-in","phone":"+52 999 555 9931","email":"lucia.torres85@familia.mx","guardian":"Mariana Torres","allergies":[],"chronicCare":["ADHD"],"activity":{"kind":"today","status":"Checked-in","time":"02:00 PM"}},
  {"id":"p86","name":"Leonardo Antonio Cabrera Soto","mrn":"MRN-2026-04-001072","age":"1 Yrs 05 months","dob":"05/08/2025","sex":"M","swatch":5,"isNew":false,"loc":"chavitos","pract":"ariel","time":"—","status":null,"phone":"+52 999 959 6552","email":"leonardo.cabrera86@familia.mx","guardian":"Esteban Cabrera","allergies":[],"chronicCare":["Asthma (controlled)"],"activity":{"kind":"past","date":"Aug 26, 2025","daysAgo":226,"type":"Hearing screen"}},
  {"id":"p87","name":"Iván Alejandro Estrada Rojas","mrn":"MRN-2026-04-001073","age":"6 Yrs","dob":"06/25/2020","sex":"M","swatch":6,"isNew":false,"loc":"merida","pract":"miguel","time":"—","status":null,"phone":"+52 999 406 5831","email":"ivan.estrada87@familia.mx","guardian":"Esteban Estrada","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p88","name":"Teodoro Guadalupe Cabrera Ibarra","mrn":"MRN-2026-04-001074","age":"1 Yrs 02 months","dob":"03/05/2025","sex":"M","swatch":7,"isNew":false,"loc":"pensiones","pract":"miguel","time":"—","status":null,"phone":"+52 999 237 7354","email":"teodoro.cabrera88@familia.mx","guardian":"Sofía Cabrera","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Oct 25, 2025","daysAgo":166,"type":"Cardiology"}},
  {"id":"p89","name":"Lucas Rafael Bravo Ávila","mrn":"MRN-2026-04-001075","age":"5 Yrs 08 months","dob":"08/11/2020","sex":"M","swatch":0,"isNew":false,"loc":"chavitos","pract":"rafael","time":"—","status":null,"phone":"+52 999 227 3953","email":"lucas.bravo89@familia.mx","guardian":"Ricardo Bravo","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p90","name":"Valentina Andrés Méndez Gómez","mrn":"MRN-2026-04-001076","age":"3 Yrs 06 months","dob":"08/28/2022","sex":"F","swatch":1,"isNew":false,"loc":"merida","pract":"ariel","time":"—","status":null,"phone":"+52 999 483 1605","email":"valentina.mendez90@familia.mx","guardian":"Patricia Méndez","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Jan 21, 2025","daysAgo":443,"type":"Dental screen"}},
  {"id":"p91","name":"Rafael Rafael Gómez Ramírez","mrn":"MRN-2026-04-001077","age":"11 Yrs","dob":"04/02/2015","sex":"M","swatch":2,"isNew":false,"loc":"chavitos","pract":"lucia","time":"—","status":null,"phone":"+52 999 478 1927","email":"rafael.gomez91@familia.mx","guardian":"Ricardo Gómez","allergies":[],"chronicCare":[],"activity":{"kind":"upcoming","date":"Apr 25, 2026","time":"01:00 PM","type":"Annual physical","daysAhead":16}},
  {"id":"p92","name":"Esteban Iván Cortés Méndez","mrn":"MRN-2026-04-001078","age":"6 Yrs","dob":"10/16/2019","sex":"M","swatch":3,"isNew":false,"loc":"merida","pract":"lucia","time":"—","status":null,"phone":"+52 999 472 3345","email":"esteban.cortes92@familia.mx","guardian":"Andrea Cortés","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Feb 20, 2025","daysAgo":413,"type":"Wellness exam"}},
  {"id":"p93","name":"Laura Sofía Soto Vega","mrn":"MRN-2026-04-001079","age":"8 Yrs","dob":"01/21/2018","sex":"F","swatch":4,"isNew":true,"loc":"pensiones","pract":"miguel","time":"—","status":null,"phone":"+52 999 925 7660","email":"laura.soto93@familia.mx","guardian":"Andrea Soto","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p94","name":"Sara Sofía Galván Gómez","mrn":"MRN-2026-04-001080","age":"8 months","dob":"10/06/2025","sex":"F","swatch":5,"isNew":false,"loc":"chavitos","pract":"miguel","time":"—","status":null,"phone":"+52 999 172 8831","email":"sara.galvan94@familia.mx","guardian":"Manuel Galván","allergies":[],"chronicCare":["Sickle cell trait"],"activity":{"kind":"upcoming","date":"May 7, 2026","time":"01:00 PM","type":"Follow-up","daysAhead":28}},
  {"id":"p95","name":"Catalina Guadalupe López Rojas","mrn":"MRN-2026-04-001081","age":"2 Yrs 06 months","dob":"09/03/2023","sex":"F","swatch":6,"isNew":true,"loc":"pensiones","pract":"miguel","time":"—","status":null,"phone":"+52 999 939 2505","email":"catalina.lopez95@familia.mx","guardian":"Patricia López","allergies":[],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p96","name":"Vanessa Fernando Fuentes Hernández","mrn":"MRN-2026-04-001082","age":"13 Yrs","dob":"12/06/2012","sex":"F","swatch":7,"isNew":true,"loc":"merida","pract":"ariel","time":"—","status":null,"phone":"+52 999 821 6648","email":"vanessa.fuentes96@familia.mx","guardian":"Ricardo Fuentes","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Nov 4, 2024","daysAgo":521,"type":"Cardiology"}},
  {"id":"p97","name":"Camila Antonio Jiménez Guerrero","mrn":"MRN-2026-04-001083","age":"8 Yrs","dob":"10/06/2018","sex":"F","swatch":0,"isNew":true,"loc":"pensiones","pract":"rafael","time":"—","status":null,"phone":"+52 999 431 4775","email":"camila.jimenez97@familia.mx","guardian":"Elena Jiménez","allergies":["Dust mites"],"chronicCare":[],"activity":{"kind":"none"}},
  {"id":"p98","name":"Octavio Alejandro López Gómez","mrn":"MRN-2026-04-001084","age":"12 Yrs","dob":"11/12/2013","sex":"M","swatch":1,"isNew":true,"loc":"chavitos","pract":"ariel","time":"—","status":null,"phone":"+52 999 482 3633","email":"octavio.lopez98@familia.mx","guardian":"Patricia López","allergies":["Latex"],"chronicCare":[],"activity":{"kind":"upcoming","date":"Apr 23, 2026","time":"08:30 AM","type":"Telehealth","daysAhead":14}},
  {"id":"p99","name":"Jimena Eugenia Cortés Salinas","mrn":"MRN-2026-04-001085","age":"3 Yrs 08 months","dob":"10/14/2022","sex":"F","swatch":2,"isNew":true,"loc":"merida","pract":"ariel","time":"—","status":null,"phone":"+52 999 471 3665","email":"jimena.cortes99@familia.mx","guardian":"Elena Cortés","allergies":[],"chronicCare":[],"activity":{"kind":"past","date":"Dec 24, 2024","daysAgo":471,"type":"Wellness exam"}},
  {"id":"p100","name":"Lucas José Navarro Herrera","mrn":"MRN-2026-04-001086","age":"15 Yrs","dob":"03/25/2010","sex":"M","swatch":3,"isNew":false,"loc":"pensiones","pract":"ariel","time":"—","status":null,"phone":"+52 999 503 5682","email":"lucas.navarro100@familia.mx","guardian":"Alejandra Navarro","allergies":[],"chronicCare":["Asthma (controlled)"],"activity":{"kind":"none"}},
];

// Vitals timeline for patient detail
const VITALS_HISTORY = {
  weight:  [{d:"Jan",v:13.2},{d:"Feb",v:13.6},{d:"Mar",v:13.9},{d:"Apr",v:14.3}],
  height:  [{d:"Jan",v:96 },{d:"Feb",v:97 },{d:"Mar",v:98 },{d:"Apr",v:99 }],
  temp:    36.6,
  hr:      102,
  spo2:    98,
  bp:      "96/62",
};

const VISITS = [
  { date: "Apr 9, 2026",  time: "10:30 AM", type: "Well-child visit", pract: "miguel", loc: "chavitos",  summary: "Routine check-up. Growth on track. Boosters updated.",                                   status: "Today",       reason: "Annual well-child exam · age-appropriate developmental screening" },
  { date: "Mar 18, 2026", time: "02:15 PM", type: "Follow-up",        pract: "ariel",  loc: "chavitos",  summary: "Follow-up rescheduled by family — daughter was traveling.",                                status: "Rescheduled", reason: "Asthma management follow-up", rescheduledTo: "May 04, 2026" },
  { date: "Feb 28, 2026", time: "09:00 AM", type: "Vaccination",      pract: "lucia",  loc: "pensiones", summary: "Cancelled by clinic — provider out sick. Family notified, re-booked.",                     status: "Cancelled",   reason: "Routine vaccination" },
  { date: "Jan 14, 2026", time: "11:00 AM", type: "Sick visit",       pract: "ariel",  loc: "chavitos",  summary: "URI, supportive care recommended. No antibiotics.",                                        status: "Completed",   reason: "Cough, low-grade fever for 3 days",
    notes: { chief: "Cough × 3 days, low-grade fever, runny nose. No respiratory distress.",
             exam: "T 37.6°C · HR 118 · RR 24 · SpO₂ 98%. Tympanic membranes clear. Mild pharyngeal erythema, no exudate. Chest clear to auscultation.",
             dx:   "Upper respiratory infection (viral)",
             plan: "Supportive care: oral fluids, rest, saline nasal drops. Acetaminophen 10 mg/kg q6h PRN for fever ≥38°C. Return if SOB, fever >39°C, or symptoms persist >7 days.",
             rx:   [{ name: "Acetaminophen syrup 160mg/5mL", dose: "5 mL q6h PRN fever" }],
             imms: [],
             next: "PRN — call if not improving in 5–7 days." }
  },
  { date: "Oct 22, 2025", time: "10:00 AM", type: "Well-child visit", pract: "miguel", loc: "chavitos",  summary: "Annual physical. Vision and hearing screen passed.",                                       status: "Completed",   reason: "Annual physical exam",
    notes: { chief: "Annual well-child exam. No parental concerns. Eating, sleeping, growth all reported as normal.",
             exam: "T 36.8°C · HR 100 · BP 95/60 · Vision 20/30 OU · Hearing pass bilaterally. Growth: weight & height at 50th percentile.",
             dx:   "Healthy child, age-appropriate development",
             plan: "Continue balanced diet, 1h+ daily physical activity, sleep 10–12h. Schedule dental check.",
             rx:   [],
             imms: [{ name: "Influenza (annual)", lot: "FL-2025-3344", site: "Right deltoid" }],
             next: "Next well-child visit in 12 months." }
  },
  { date: "Jun 03, 2025", time: "09:45 AM", type: "Vaccination",      pract: "ariel",  loc: "chavitos",  summary: "MMR booster administered. No adverse reaction.",                                           status: "Completed",   reason: "MMR booster",
    notes: { chief: "Scheduled MMR booster.",
             exam: "Afebrile. Well-appearing. No active complaints.",
             dx:   "Routine immunization",
             plan: "Observed 15 min post-vaccine — no reaction. Acetaminophen if low-grade fever in next 24h.",
             rx:   [],
             imms: [{ name: "MMR", lot: "BV-11223", site: "Left deltoid" }],
             next: "Varicella booster in 4 weeks." }
  },
];

const MEDICATIONS = [
  { name: "Salbutamol inhaler",   dose: "100 mcg PRN",     status: "Active",  by: "Dr. Miguel Soto", start: "Jan 14, 2026" },
  { name: "Loratadine",           dose: "5 mg daily",      status: "Active",  by: "Dr. Ariel Castillo", start: "Mar 02, 2026" },
  { name: "Amoxicillin 250mg/5ml",dose: "5 ml × 7 days",    status: "Completed", by: "Dr. Ariel Castillo", start: "Oct 22, 2025" },
];

const IMMUNIZATIONS = [
  { name: "DTaP",      date: "Mar 12, 2026", lot: "AX-29841", by: "Dr. Miguel Soto" },
  { name: "MMR",       date: "Jun 03, 2025", lot: "BV-11223", by: "Dr. Ariel Castillo" },
  { name: "Varicella", date: "Jun 03, 2025", lot: "BV-11224", by: "Dr. Ariel Castillo" },
  { name: "Hep B",     date: "Jan 22, 2023", lot: "QQ-88472", by: "Dr. Lucía Hernández" },
];

const TASKS = [
  { id: "t1", title: "Call Mariana Cruz re: Diego's lab results", due: "Today, 11:00", priority: "high",   assignee: "Aminata", done: false },
  { id: "t2", title: "Send invoice INV-2026-0419 to Ortega family", due: "Today",      priority: "medium", assignee: "Aminata", done: false },
  { id: "t3", title: "Confirm tomorrow's morning appointments (8)", due: "Today, 17:00", priority: "high", assignee: "Aminata", done: false },
  { id: "t4", title: "Order Salbutamol inhaler refill - 6 units",   due: "Tomorrow",   priority: "low",    assignee: "Pharmacy", done: false },
  { id: "t5", title: "File vaccine consent forms for week of Apr 6", due: "Yesterday", priority: "medium", assignee: "Aminata", done: true },
  { id: "t6", title: "Update insurance info for Hernández family",  due: "Apr 12",    priority: "low",    assignee: "Aminata", done: false },
];

const INVOICES = [
  { id: "INV-2026-0419", patient: "p4", amount: 1850, status: "Paid",    date: "Apr 09, 2026", method: "Card", items: 3 },
  { id: "INV-2026-0418", patient: "p2", amount: 950,  status: "Paid",    date: "Apr 09, 2026", method: "Cash", items: 2 },
  { id: "INV-2026-0417", patient: "p1", amount: 2400, status: "Pending", date: "Apr 09, 2026", method: "—",    items: 4 },
  { id: "INV-2026-0416", patient: "p3", amount: 1200, status: "Pending", date: "Apr 09, 2026", method: "—",    items: 2 },
  { id: "INV-2026-0415", patient: "p7", amount: 800,  status: "Overdue", date: "Apr 02, 2026", method: "—",    items: 1 },
  { id: "INV-2026-0414", patient: "p6", amount: 3200, status: "Paid",    date: "Apr 01, 2026", method: "Transfer", items: 5 },
  { id: "INV-2026-0413", patient: "p5", amount: 1100, status: "Paid",    date: "Mar 28, 2026", method: "Card", items: 2 },
  { id: "INV-2026-0412", patient: "p8", amount: 2700, status: "Draft",   date: "Mar 27, 2026", method: "—",    items: 3 },
];

const INVOICE_LINE_ITEMS = [
  { code: "C-001", name: "Pediatric consultation",   qty: 1, price: 800 },
  { code: "V-204", name: "DTaP vaccination",         qty: 1, price: 650 },
  { code: "L-117", name: "Complete blood count",     qty: 1, price: 400 },
  { code: "P-008", name: "Pulse oximetry screening", qty: 1, price: 150 },
];

const MESSAGES = [
  { id: "m1", from: "Mariana Cruz",     role: "Parent",          last: "Buenas, ¿podemos mover la cita de Diego al jueves?", time: "10:42 AM", unread: 2, online: true,  color: "#FECDD3" },
  { id: "m2", from: "Dr. Miguel Soto",  role: "Practitioner",    last: "Por favor confirma el lote del DTaP antes de las 11.", time: "10:18 AM", unread: 1, online: true,  color: "#BAE6FD" },
  { id: "m3", from: "Andrea Romero",    role: "Parent",          last: "Adjunto el comprobante del depósito de la factura.", time: "09:55 AM", unread: 0, online: false, color: "#FDE68A" },
  { id: "m4", from: "Pharmacy — CVS",   role: "External",        last: "Refill ready for pickup: Salbutamol × 6.",            time: "09:30 AM", unread: 0, online: false, color: "#A7F3D0" },
  { id: "m5", from: "Dr. Ariel C.",     role: "Practitioner",    last: "Voy a llegar 15 min tarde, avisa a los pacientes.",  time: "08:48 AM", unread: 0, online: true,  color: "#DDD6FE" },
  { id: "m6", from: "Sofía Castillo",   role: "Parent",          last: "Muchas gracias por la atención de ayer 💙",          time: "Yesterday", unread: 0, online: false, color: "#FBCFE8" },
];

const MESSAGE_THREAD = [
  { from: "them", text: "Buenas tardes Aminata", time: "10:38 AM" },
  { from: "them", text: "¿Podemos mover la cita de Diego al jueves? Tengo una junta el viernes 😕", time: "10:39 AM" },
  { from: "me",   text: "¡Hola Mariana! Claro, déjame revisar la agenda del Dr. Miguel.", time: "10:41 AM" },
  { from: "them", text: "Mil gracias", time: "10:42 AM" },
];

const STICKY_NOTES = [
  { id: "n1", color: "#FEF3C7", text: "Pedir a Pharmacy 6× Salbutamol refill — Diego", tag: "Pharmacy" },
  { id: "n2", color: "#DBEAFE", text: "Recordar a Dr. Miguel: revisar resultados de Ximena antes de las 14:00", tag: "Clinical" },
  { id: "n3", color: "#FCE7F3", text: "Cumpleaños de Renata el viernes 🎂 — mandar tarjetita", tag: "Personal" },
  { id: "n4", color: "#D1FAE5", text: "Imprimir formularios de consentimiento de vacunación (10 copias)", tag: "Admin" },
  { id: "n5", color: "#FED7AA", text: "Llamar a proveedores de insumos médicos — pedido mensual", tag: "Admin" },
  { id: "n6", color: "#E0E7FF", text: "Revisar con contadora antes del cierre mensual (30 abr)", tag: "Finance" },
];

const REMEDY_SUGGESTIONS = [
  "Show me today's no-shows and draft follow-up messages",
  "Summarize Diego Martínez Cruz's chart for me",
  "Which invoices are overdue more than 15 days?",
  "Generate a vaccine reminder for parents of patients aged 4–6",
];

window.CHAVITOS = {
  STATUS_STYLES, LOCATIONS, PRACTITIONERS, SWATCH, PATIENTS,
  VITALS_HISTORY, VISITS, MEDICATIONS, IMMUNIZATIONS, TASKS,
  INVOICES, INVOICE_LINE_ITEMS, MESSAGES, MESSAGE_THREAD,
  STICKY_NOTES, REMEDY_SUGGESTIONS,
};
